services:
  nginx:
    image: nginx:1.29.0-alpine
    container_name: rinha-nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - sockets:/tmp:rw
    ports:
      - "9999:80"
    networks:
      - backend
    depends_on:
      - rinha-gateway-1
      - rinha-gateway-2
    deploy:
      resources:
        limits:
          cpus: "0.3"
          memory: "50MB"
  rinha-gateway-1:
    image: daniloneto/rinha-gateway:latest
    container_name: rinha-gateway-1
    volumes:
      - sockets:/tmp:rw
      - sockets:/sockets:rw
    environment:
      - SOCKET_PATH=/tmp/gateway-1.sock
    networks:
      - backend
      - payment-processor
    depends_on:
      - rinha-db
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "125MB"

  rinha-gateway-2:
    image: daniloneto/rinha-gateway:latest
    container_name: rinha-gateway-2
    volumes:
      - sockets:/tmp:rw
      - sockets:/sockets:rw
    environment:
      - SOCKET_PATH=/tmp/gateway-2.sock
    networks:
      - backend
      - payment-processor
    depends_on:
      - rinha-db
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "125MB"
  rinha-db:
    image: daniloneto/rinha-database:latest
    container_name: rinha-db
    volumes:
      - sockets:/sockets:rw
    environment:
      - SOCKET_PATH=/sockets/database.sock
    networks:
      - backend
    deploy:
      resources:
        limits:
          cpus: "0.7"
          memory: "300MB"

networks:
  backend:
    driver: bridge
  payment-processor:
    external: true
    name: payment-processor

volumes:
  sockets:
