x-api_template: &api_template
  build:
    context: ./gateway
    dockerfile: Dockerfile
  volumes:
    - sockets:/tmp:rw
    - sockets:/sockets:rw
  networks:
    - backend
    - payment-processor
  deploy:
    resources:
      limits:
        cpus: "0.5"
        memory: "115MB"
services:
  nginx:
    image: nginx:1.29.0-alpine
    container_name: rinha-nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - sockets:/tmp:rw
    ports:
      - "9999:80"
    networks:
      - backend
    depends_on:
      - rinha-gateway-1
      - rinha-gateway-2
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: "60MB"
  rinha-gateway-1:
    <<: *api_template
    container_name: rinha-gateway-1
    hostname: rinha-gateway-1
    environment:
      - SOCKET_PATH=/tmp/gateway-1.sock
      - MaxConnectionsPerServer=256 
      - WorkerMultiplier=1
      - RetryBaseDelayMs=200
      - PooledConnectionLifetimeMinutes=5
      - DbTimeoutSeconds=5
      - RetryMaxDelayMs=1000
      - HealthCheckIntervalSeconds=2
    ports:
      - "9001:9001"
    depends_on:
      - rinha-db

  rinha-gateway-2:
    <<: *api_template
    container_name: rinha-gateway-2
    hostname: rinha-gateway-2
    environment:
      - SOCKET_PATH=/tmp/gateway-2.sock
      - MaxConnectionsPerServer=256 
      - WorkerMultiplier=1
      - RetryBaseDelayMs=200
      - PooledConnectionLifetimeMinutes=5
      - DbTimeoutSeconds=5
      - RetryMaxDelayMs=1000
      - HealthCheckIntervalSeconds=2
    ports:
      - "9002:9002"
    depends_on:
      - rinha-db
  rinha-db:
    build:
      context: ./database
      dockerfile: Dockerfile
    container_name: rinha-db
    volumes:
      - sockets:/sockets:rw
    environment:
      - SOCKET_PATH=/sockets/database.sock
      - MaxCapacity=100000    
    networks:
      - backend
    deploy:
      resources:
        limits:
          cpus: "0.3"
          memory: "60MB"

networks:
  backend:
    driver: bridge
  payment-processor:
    external: true
    name: payment-processor

volumes:
  sockets:
